# Example of a full infrastructure stack
#
# Note, this file is not suitable for a production deployment. It is only an
# example of all the infrastructure components needed in a real production
# deployment.
#
# Usage::
#
#   $ docker-compose up -f docker-compose.yml -d
#
# Following services are included:
# - Frontend: Nginx (exposed ports: 80 and 443)
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL/MySQL) (exposed port: 5432 or 3306)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - Search platform: (OpenSearch/Elasticsearch) (exposed ports: 9200, 9300)
# - OpenSearch Dashboard/Kibana (view OS/ES indexes) (exposed ports: 5601)
#
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
    volumes:
      - cache_data:/data
  db:
    extends:
      file: docker-services.yml
      service: db
    volumes:
      - database_data:/var/lib/postgresql/data
  mq:
    extends:
      file: docker-services.yml
      service: mq
    volumes:
      - mq_data:/var/lib/rabbitmq
  search:
    extends:
      file: docker-services.yml
      service: search
    volumes:
      - search_data:/usr/share/opensearch/data
  opensearch-dashboards:
    extends:
      file: docker-services.yml
      service: opensearch-dashboards
  pgadmin:
    extends:
      file: docker-services.yml
      service: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    container_name: invenio-frontend
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - /${INVENIO_LOCAL_INSTANCE_PATH}/static:/opt/invenio/var/instance/static
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
volumes:
  # archived_data:
  # static_data:
  # uploaded_data:
  database_data:
  cache_data:
  mq_data:
  search_data:
  pgadmin_data: