"""Tests for communities index mapping updates."""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest
from click.testing import CliRunner
from invenio_communities.proxies import current_communities
from invenio_rdm_records.records.api import RDMDraft, RDMRecord
from invenio_records_resources.services.custom_fields.mappings import Mapping
from invenio_search import current_search_client
from invenio_search.engine import dsl
from invenio_search.proxies import current_search
from invenio_search.utils import build_alias_name
from kcworks.services.communities.cli import update_index_mapping
from kcworks.services.search.mappings_utilities import additive_mapping_properties


def test_additive_mapping_properties_adds_missing_leaf() -> None:
    """Missing top-level and nested properties are included in the patch."""
    old = {
        "theme": {
            "type": "object",
            "properties": {
                "enabled": {"type": "boolean"},
            },
        }
    }
    new = {
        "theme": {
            "type": "object",
            "properties": {
                "enabled": {"type": "boolean"},
                "autogeneratedLogo": {"type": "boolean"},
            },
        },
        "files": {"type": "object"},
    }
    patch, warnings = additive_mapping_properties(old, new)
    assert warnings == []
    assert patch["files"] == {"type": "object"}
    assert patch["theme"]["properties"]["autogeneratedLogo"] == {"type": "boolean"}


def test_additive_mapping_properties_skips_live_only_fields() -> None:
    """Live-only custom field properties are not removed or reported as errors."""
    old = {
        "custom_fields": {
            "type": "object",
            "properties": {
                "stats:dashboard_enabled": {"type": "boolean"},
            },
        }
    }
    new = {"custom_fields": {"type": "object"}}
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert warnings == []


def test_additive_mapping_properties_skips_dynamic_object_undeclared_children() -> None:
    """OS-only children under a dynamic object omitted from the file are ignored."""
    old = {
        "locale_titles": {
            "type": "object",
            "dynamic": "true",
            "properties": {"de": {"type": "text"}},
        }
    }
    new = {"locale_titles": {"type": "object", "dynamic": "true"}}
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert warnings == []


def test_additive_mapping_properties_warns_on_closed_object_live_children() -> None:
    """OS-only children under a non-dynamic object are reported as a conflict."""
    old = {
        "closed": {
            "type": "object",
            "dynamic": "false",
            "properties": {"extra": {"type": "keyword"}},
        }
    }
    new = {"closed": {"type": "object", "dynamic": "false"}}
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert len(warnings) == 1
    assert "closed" in warnings[0]


def test_additive_mapping_properties_warns_on_conflicting_leaf() -> None:
    """Conflicting leaf mappings are skipped with a warning."""
    old = {"metadata": {"properties": {"title": {"type": "text"}}}}
    new = {
        "metadata": {
            "properties": {
                "title": {
                    "type": "text",
                    "search_analyzer": "accent_edge_analyzer",
                }
            }
        }
    }
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert len(warnings) == 1
    assert "metadata.title" in warnings[0]


def _communities_index() -> dsl.Index:
    return dsl.Index(
        build_alias_name(current_communities.service.config.record_cls.index._name),
        using=current_search_client,
    )


def _rdm_records_index() -> dsl.Index:
    return dsl.Index(
        build_alias_name(RDMRecord.index._name),
        using=current_search_client,
    )


def _rdm_drafts_index() -> dsl.Index:
    return dsl.Index(
        build_alias_name(RDMDraft.index._name),
        using=current_search_client,
    )


def _strip_autogenerated_logo(properties: dict) -> dict:
    """Return a copy of `properties` without `theme.autogeneratedLogo` leaves."""
    props = copy.deepcopy(properties)
    theme_props = props.get("theme", {}).get("properties", {})
    if isinstance(theme_props, dict):
        theme_props.pop("autogeneratedLogo", None)
    parent_theme_props = (
        props.get("parent", {})
        .get("properties", {})
        .get("theme", {})
        .get("properties", {})
    )
    if isinstance(parent_theme_props, dict):
        parent_theme_props.pop("autogeneratedLogo", None)
    return props


def _strip_record_embedded_autogenerated_logo(properties: dict) -> dict:
    """Return a copy without embedded community `theme.autogeneratedLogo` leaves."""
    props = copy.deepcopy(properties)
    entries = (
        props.get("parent", {})
        .get("properties", {})
        .get("communities", {})
        .get("properties", {})
        .get("entries", {})
        .get("properties", {})
    )
    if not isinstance(entries, dict):
        return props
    theme_props = entries.get("theme", {}).get("properties", {})
    if isinstance(theme_props, dict):
        theme_props.pop("autogeneratedLogo", None)
    parent_theme_props = (
        entries.get("parent", {})
        .get("properties", {})
        .get("theme", {})
        .get("properties", {})
    )
    if isinstance(parent_theme_props, dict):
        parent_theme_props.pop("autogeneratedLogo", None)
    return props


def _recreate_index_without_autogenerated_logo(
    record_index_name: str,
    *,
    strip_properties,
) -> None:
    """Recreate an index as if ``autogeneratedLogo`` were not yet mapped."""
    alias_name = build_alias_name(record_index_name)
    index_dict = current_search_client.indices.get(index=alias_name)
    physical_name = list(index_dict.keys())[0]

    mapping_path = Path(current_search.mappings[record_index_name])
    with mapping_path.open(encoding="utf-8") as body:
        create_body = json.load(body)
    create_body["mappings"]["properties"] = strip_properties(
        create_body["mappings"]["properties"]
    )

    current_search_client.indices.delete(index=physical_name)
    current_search_client.indices.create(index=physical_name, body=create_body)
    current_search_client.indices.put_alias(index=physical_name, name=alias_name)


def _simulate_pre_migration_communities_index() -> None:
    """Recreate the communities index as if `autogeneratedLogo` were not yet mapped.

    Fresh test indices are built from the registered mapping JSON, which now
    includes `theme.autogeneratedLogo`. Migration-focused CLI tests need an
    older mapping shape instead.
    """
    _recreate_index_without_autogenerated_logo(
        current_communities.service.config.record_cls.index._name,
        strip_properties=_strip_autogenerated_logo,
    )


def _simulate_pre_migration_rdm_records_index() -> None:
    """Recreate the RDM records index without embedded theme.autogeneratedLogo."""
    _recreate_index_without_autogenerated_logo(
        RDMRecord.index._name,
        strip_properties=_strip_record_embedded_autogenerated_logo,
    )


@pytest.fixture
def pre_migration_communities_index(running_app, search_clear):
    """Communities index without `theme.autogeneratedLogo` mapping leaves."""
    _simulate_pre_migration_communities_index()


@pytest.fixture
def pre_migration_rdm_records_index(running_app, search_clear):
    """RDM records index without embedded community theme.autogeneratedLogo."""
    _simulate_pre_migration_rdm_records_index()


def test_update_index_mapping_applies_autogenerated_logo(
    pre_migration_communities_index,
    pre_migration_rdm_records_index,
) -> None:
    """CLI adds theme.autogeneratedLogo from the registered mapping files."""
    communities_index = _communities_index()
    records_index = _rdm_records_index()
    assert not Mapping.field_exists("theme.autogeneratedLogo", communities_index)
    assert not Mapping.field_exists(
        "parent.communities.entries.theme.autogeneratedLogo", records_index
    )

    runner = CliRunner()
    result = runner.invoke(update_index_mapping, [])
    assert result.exit_code == 0, result.output
    assert "communities index mapping updated" in result.output.lower()

    assert Mapping.field_exists("theme.autogeneratedLogo", communities_index)
    assert Mapping.field_exists("parent.theme.autogeneratedLogo", communities_index)
    assert Mapping.field_exists(
        "parent.communities.entries.theme.autogeneratedLogo", records_index
    )
    assert Mapping.field_exists(
        "parent.communities.entries.parent.theme.autogeneratedLogo", records_index
    )


def test_update_index_mapping_is_idempotent(
    pre_migration_communities_index,
    pre_migration_rdm_records_index,
) -> None:
    """A second run reports the mapping is already up to date."""
    runner = CliRunner()
    first = runner.invoke(update_index_mapping, [])
    assert first.exit_code == 0, first.output
    assert "index mapping updated" in first.output.lower()

    second = runner.invoke(update_index_mapping, [])
    assert second.exit_code == 0, second.output
    assert second.output.lower().count("already up to date") >= 2


def test_update_index_mapping_dry_run(
    pre_migration_communities_index,
    pre_migration_rdm_records_index,
) -> None:
    """`--dry-run` prints the patch without changing the mapping."""
    communities_index = _communities_index()
    records_index = _rdm_records_index()
    runner = CliRunner()
    result = runner.invoke(update_index_mapping, ["--dry-run"])
    assert result.exit_code == 0, result.output
    assert "would put_mapping" in result.output.lower()
    assert "autogeneratedLogo" in result.output
    assert not Mapping.field_exists("theme.autogeneratedLogo", communities_index)
    assert not Mapping.field_exists(
        "parent.communities.entries.theme.autogeneratedLogo", records_index
    )
