"""Tests for communities index mapping updates."""

from __future__ import annotations

from click.testing import CliRunner
from invenio_communities.proxies import current_communities
from invenio_records_resources.services.custom_fields.mappings import Mapping
from invenio_search import current_search_client
from invenio_search.engine import dsl
from invenio_search.utils import build_alias_name
from kcworks.services.communities.cli import update_index_mapping
from kcworks.services.communities.index_mapping import additive_mapping_properties


def test_additive_mapping_properties_adds_missing_leaf() -> None:
    """Missing top-level and nested properties are included in the patch."""
    old = {
        "theme": {
            "type": "object",
            "properties": {
                "enabled": {"type": "boolean"},
            },
        }
    }
    new = {
        "theme": {
            "type": "object",
            "properties": {
                "enabled": {"type": "boolean"},
                "autogeneratedLogo": {"type": "boolean"},
            },
        },
        "files": {"type": "object"},
    }
    patch, warnings = additive_mapping_properties(old, new)
    assert warnings == []
    assert patch["files"] == {"type": "object"}
    assert patch["theme"]["properties"]["autogeneratedLogo"] == {"type": "boolean"}


def test_additive_mapping_properties_skips_live_only_fields() -> None:
    """Live-only custom field properties are not removed or reported as errors."""
    old = {
        "custom_fields": {
            "type": "object",
            "properties": {
                "stats:dashboard_enabled": {"type": "boolean"},
            },
        }
    }
    new = {"custom_fields": {"type": "object"}}
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert warnings == []


def test_additive_mapping_properties_warns_on_conflicting_leaf() -> None:
    """Conflicting leaf mappings are skipped with a warning."""
    old = {"metadata": {"properties": {"title": {"type": "text"}}}}
    new = {
        "metadata": {
            "properties": {
                "title": {
                    "type": "text",
                    "search_analyzer": "accent_edge_analyzer",
                }
            }
        }
    }
    patch, warnings = additive_mapping_properties(old, new)
    assert patch == {}
    assert len(warnings) == 1
    assert "metadata.title" in warnings[0]


def _communities_index() -> dsl.Index:
    return dsl.Index(
        build_alias_name(current_communities.service.config.record_cls.index._name),
        using=current_search_client,
    )


def test_update_index_mapping_applies_autogenerated_logo(
    running_app, search_clear
) -> None:
    """CLI adds theme.autogeneratedLogo from the registered mapping file."""
    index = _communities_index()
    assert not Mapping.field_exists("theme.autogeneratedLogo", index)

    runner = CliRunner()
    result = runner.invoke(update_index_mapping, [])
    assert result.exit_code == 0, result.output
    assert "mapping updated" in result.output.lower()

    assert Mapping.field_exists("theme.autogeneratedLogo", index)
    assert Mapping.field_exists("parent.theme.autogeneratedLogo", index)


def test_update_index_mapping_is_idempotent(running_app, search_clear) -> None:
    """A second run reports the mapping is already up to date."""
    runner = CliRunner()
    first = runner.invoke(update_index_mapping, [])
    assert first.exit_code == 0, first.output

    second = runner.invoke(update_index_mapping, [])
    assert second.exit_code == 0, second.output
    assert "already up to date" in second.output.lower()


def test_update_index_mapping_dry_run(running_app, search_clear) -> None:
    """``--dry-run`` prints the patch without changing the mapping."""
    index = _communities_index()
    runner = CliRunner()
    result = runner.invoke(update_index_mapping, ["--dry-run"])
    assert result.exit_code == 0, result.output
    assert "would put_mapping" in result.output.lower()
    assert "autogeneratedLogo" in result.output
    assert not Mapping.field_exists("theme.autogeneratedLogo", index)
