"""Tests for the `backfill-default-branding` click command.

Uses [`click.testing.CliRunner`][click.testing.CliRunner] to invoke the
CLI against three fixture communities:

1. `branded-full` - fully branded (logo + theme present): backfill must
   leave it alone.
2. `branded-logo-only` - has a logo but no theme: backfill must seed the
   missing theme keys.
3. `branded-neither` - has neither: backfill must add both.

We also check that `--logo-only` / `--theme-only` flags isolate the
respective operations, and that admin-customized theme keys survive
backfill (only missing keys are filled).
"""

from __future__ import annotations

from io import BytesIO
from typing import Any

import pytest
from click.testing import CliRunner
from invenio_access.permissions import system_identity
from invenio_communities.proxies import current_communities
from kcworks.services.communities.cli import backfill_default_branding
from kcworks.services.communities.default_branding import (
    default_theme_style,
    generic_theme_style,
)
from kcworks.services.geopattern import derive_theme_colors

THEME_KEYS = (
    "primaryColor",
    "primaryTextColor",
    "mainHeaderBackgroundColor",
    "mainHeaderUseLogo",
    "mainHeaderUseGradient",
)


def _read_record(community_id: str) -> Any:
    """Resolve a Community record by id/slug.

    Args:
        community_id: Community UUID or slug.

    Returns:
        The raw Community record.
    """
    return current_communities.service.record_cls.pid.resolve(community_id)


def _strip_theme(community_id: str) -> None:
    """Remove the theme key from a community (simulating a pre-component record).

    Bypasses `CommunityThemeComponent` because dropping the theme via
    `service.update(..., theme=None)` would require `delete_theme`
    permission. Mutating the record + committing via a UoW is the
    cleanest way to simulate "this record was created before backend
    theming existed".
    """
    from invenio_db import db
    from invenio_records_resources.services.uow import (
        RecordCommitOp,
        UnitOfWork,
    )

    record = _read_record(community_id)
    record.pop("theme", None)
    with UnitOfWork(db.session) as uow:
        uow.register(RecordCommitOp(record))
        uow.commit()
    current_communities.service.indexer.index(record)
    current_communities.service.record_cls.index.refresh()


def _strip_logo(community_id: str) -> None:
    """Pop the logo file from a community.

    Same rationale as `_strip_theme` - simulate a community that
    predates the default-branding component.
    """
    from invenio_db import db
    from invenio_records_resources.services.uow import (
        RecordCommitOp,
        UnitOfWork,
    )

    record = _read_record(community_id)
    deleted = record.files.pop("logo", None)
    if deleted is not None:
        deleted.delete(force=True)
    with UnitOfWork(db.session) as uow:
        uow.register(RecordCommitOp(record))
        uow.commit()


@pytest.fixture(scope="function")
def three_communities(minimal_community_factory, search_clear):
    """Create three communities in distinct branding states.

    Args:
        minimal_community_factory: Fixture that produces test communities.

    Returns:
        Mapping of label to the underlying community result item.
    """
    branded_full = minimal_community_factory(slug="branded-full")
    branded_logo_only = minimal_community_factory(slug="branded-logo-only")
    branded_neither = minimal_community_factory(slug="branded-neither")

    # Strip the theme on the logo-only one. (Logo was auto-generated by
    # the component during create; we leave that alone.)
    _strip_theme(branded_logo_only.id)
    # Strip both logo and theme on the neither one.
    _strip_logo(branded_neither.id)
    _strip_theme(branded_neither.id)

    current_communities.service.record_cls.index.refresh()
    return {
        "full": branded_full,
        "logo_only": branded_logo_only,
        "neither": branded_neither,
    }


def test_backfill_dry_run_reports_correct_counts(three_communities) -> None:
    """`--dry-run` reports the right counts and writes nothing."""
    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, ["--dry-run"])
    assert result.exit_code == 0, result.output
    assert "Backfill summary (dry-run)" in result.output
    # logo_only: needs theme; neither: needs both. full: needs nothing.
    assert "touched             : 2" in result.output, result.output
    assert "needed logo         : 1" in result.output, result.output
    assert "needed theme        : 2" in result.output, result.output

    # Verify nothing actually changed on the neither community.
    record = _read_record(three_communities["neither"].id)
    assert record.files.get("logo") is None
    assert "theme" not in record or "style" not in (record.get("theme") or {})


def test_backfill_inline_applies_logo_and_theme(three_communities) -> None:
    """A non-dry-run pass fixes both logo and theme on the needy communities."""
    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, [])
    assert result.exit_code == 0, result.output

    # The "neither" community should now have logo AND theme.
    record = _read_record(three_communities["neither"].id)
    assert record.files.get("logo") is not None
    style = record["theme"]["style"]
    expected = default_theme_style("branded-neither")
    assert style["primaryColor"] == expected["primaryColor"]
    assert style["primaryTextColor"] == expected["primaryTextColor"]
    assert style["mainHeaderBackgroundColor"] == expected["mainHeaderBackgroundColor"]

    # The "logo_only" community should now also have theme keys.
    record = _read_record(three_communities["logo_only"].id)
    style = record["theme"]["style"]
    expected = derive_theme_colors("branded-logo-only")
    assert style["primaryColor"] == expected["primaryColor"]
    assert style["primaryTextColor"] == expected["primaryTextColor"]
    assert style["mainHeaderBackgroundColor"] == expected["mainHeaderBackgroundColor"]

    # The "full" community should be untouched (its theme was already set
    # by the create-time component to the slug-derived defaults).
    record = _read_record(three_communities["full"].id)
    style = record["theme"]["style"]
    expected = derive_theme_colors("branded-full")
    assert style["primaryColor"] == expected["primaryColor"]
    assert style["primaryTextColor"] == expected["primaryTextColor"]
    assert style["mainHeaderBackgroundColor"] == expected["mainHeaderBackgroundColor"]


def test_backfill_logo_only_skips_theme(three_communities) -> None:
    """`--logo-only` adds the logo on `neither` but leaves theme empty."""
    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, ["--logo-only"])
    assert result.exit_code == 0, result.output

    record = _read_record(three_communities["neither"].id)
    assert record.files.get("logo") is not None
    # Theme should still be absent because we asked for logo-only.
    theme = record.get("theme") or {}
    assert (theme.get("style") or {}) == {}


def test_backfill_theme_only_skips_logo(three_communities) -> None:
    """`--theme-only` adds theme on `neither` but does not generate the logo."""
    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, ["--theme-only"])
    assert result.exit_code == 0, result.output

    record = _read_record(three_communities["neither"].id)
    style = (record.get("theme") or {}).get("style") or {}
    expected = default_theme_style("branded-neither")
    assert style.get("primaryColor") == expected["primaryColor"]
    assert style.get("primaryTextColor") == expected["primaryTextColor"]
    assert (
        style.get("mainHeaderBackgroundColor")
        == expected["mainHeaderBackgroundColor"]
    )
    # Logo file is still absent because we asked for theme-only.
    assert record.files.get("logo") is None


def test_backfill_preserves_admin_theme_value(
    minimal_community_factory,
    search_clear,
) -> None:
    """An admin-customized theme key survives backfill (only missing keys filled)."""
    community = minimal_community_factory(slug="branded-admin-custom")
    # Push a custom primary color through the regular update path. Read via
    # the service so `update_data` is the schema-shaped payload (`slug`,
    # `access`, `metadata`, ...); the raw record dict from `pid.resolve`
    # lacks those top-level fields and the update schema rejects it.
    read_result = current_communities.service.read(system_identity, community.id)
    update_data = dict(read_result.data)
    update_data["theme"] = {
        "enabled": True,
        "style": {"primaryColor": "#abcdef"},
    }
    current_communities.service.update(system_identity, community.id, update_data)
    current_communities.service.record_cls.index.refresh()

    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, [])
    assert result.exit_code == 0, result.output

    record = _read_record(community.id)
    style = record["theme"]["style"]
    assert style["primaryColor"] == "#abcdef"  # admin value preserved
    expected = derive_theme_colors("branded-admin-custom")
    # The two missing keys must have been topped up to slug-derived
    # defaults (even though the admin had overridden primaryColor).
    assert style["primaryTextColor"] == expected["primaryTextColor"]
    assert style["mainHeaderBackgroundColor"] == expected["mainHeaderBackgroundColor"]


def test_backfill_uses_generic_theme_for_custom_logo(
    minimal_community_factory,
    search_clear,
) -> None:
    """Backfill seeds generic colors when the logo is user-uploaded."""
    community = minimal_community_factory(slug="branded-custom-logo")
    current_communities.service.update_logo(
        system_identity,
        community.id,
        BytesIO(b"custom-logo-bytes"),
    )
    _strip_theme(community.id)

    runner = CliRunner()
    result = runner.invoke(backfill_default_branding, [])
    assert result.exit_code == 0, result.output

    record = _read_record(community.id)
    style = record["theme"]["style"]
    expected = generic_theme_style()
    assert style["primaryColor"] == expected["primaryColor"]
    assert style["primaryTextColor"] == expected["primaryTextColor"]
    assert (
        style["mainHeaderBackgroundColor"] == expected["mainHeaderBackgroundColor"]
    )
    assert record["theme"].get("autogeneratedLogo") is False
