name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  REGISTRY: ghcr.io
  IMAGE_NAME: kcworks

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      # Cache docker images so they don't rebuild every time
      # - name: Cache Local Images
      #   id: local-images
      #   uses: actions/cache@v3
      #   with:
      #     path: /var/lib/docker/
      #     key: local-docker-directory

      - name: Build Images
        run: |
          docker compose up -d --build

      # - name: Set up services
      #   run: |
      #     docker exec -it knowledgecommonsworks_web-ui_1 bash -c "bash ./scripts/setup-services.sh"
      #     exit

      # - name: Build statics and assets
      #   run: |
      #     docker exec -it knowledgecommonsworks_web-ui_1 bash -c "bash ./scripts/build-assets.sh"
      #     exit

      # - name: Run unit tests
      #   run: cd site && pytest

      - name: Stop services
        if: always()
        run: |
          docker compose down

